### ISSUE TITLE
Add an xstate comparison

### ISSUE THREAD

**Issue by matthewp** [matthewp/robot#22]

**Comment by RiZKiT** [comment]
Just as a followup, there is [@xstate/fsm](https://github.com/davidkpiano/xstate/tree/master/packages/xstate-fsm) / [xstate-fsm docs](https://xstate.js.org/docs/packages/xstate-fsm/) which is the bare minimum version of xstate. I wanted to use this one until I stumbled upon yours. 
Would be nice if you could add this to your comparison, because it seems to be a bit more fair, regarding the size.

**Comment by matthewp** [comment]
@RiZKiT Thanks for the suggestion, I might do that. Note that Robot is comparable to XState in features; `@xstate/fsm` is more bare-bones. If xstate/fsm had all of the features of XState they would tell you to use that instead, right?

**Comment by jamesopstad** [comment]
As someone just weighing up the options, it would be useful to know what `robot` can do that `@xstate/fsm` can't. I think it takes quite a bit of digging and a good understanding of the terminology to figure this out at the moment.

**Comment by matthewp** [comment]
The XState FSM page says the things that it cannot do: https://github.com/davidkpiano/xstate/tree/master/packages/xstate-fsm

Robot can do almost all of those things. Robot is not a minimal FSM implementation, which is why I don't compare it to those things.
