### ISSUE TITLE
Distribution in CJS / UMD format

### ISSUE THREAD

**Issue by danburzo** [matthewp/robot#40]
Hi Matthew,

Following up on [the Twitter conversation](https://twitter.com/danburzo/status/1175457092007862272), I'm opening this issue about packaging for use in Node and (older) browsers.

I can add a Rollup config to build CJS / UMD bundles in a PR, but I noticed the use of `"type": "module"` in package.json ([TIL!](https://medium.com/@nodejs/announcing-a-new-experimental-modules-1be8d2d6c2ff)), and I'm not sure how making the `main` field point to CJS and `module` point to ES can impact people's setups...

**Comment by matthewp** [comment]
Hey @danburzo! I wouldn't expect there to be any impact by making this change. If someone complains we can just do a major version bump (actually minor since this is pre-1.0). So happy to take a PR!

I'm thinking maybe only CJS at the moment. The source code is written in ES6 and I don't want to add an ES5 build at the moment at least. People can transpile it to ES5 in their own projects. Since all browsers that support ES6 also support modules there's no need for UMD.

Thanks! 😀

**Comment by danburzo** [comment]
Made Rollup build the files in CJS format. However, 'robot3/debug' still resolves to the `debug.js` file in the root folder. Node people would have to `require("robot3/dist/debug.js")` instead...

**Comment by matthewp** [comment]
Yeah that sounds fine for me at the moment at least, thanks!
