### ISSUE TITLE
Async transition guards

### ISSUE THREAD

**Issue by victortwc** [matthewp/robot#97]
Pretty cool lib!

Is it possible to have guards returning promises, so it will only transition if the promise guard resolves?

e.g:

```
// Only allow submission of a login and password is entered.
async function canSubmit(ctx) {
  return fetch(`/api/verify/${ctx.login}`);
}

const machine = createMachine({
  idle: state(
    transition('submit', 'complete',
      guard(canSubmit)
    )
  ),
  complete: state()
});
```

I understand that Actions are the place where we are supposed to do side effects, but sometimes we have side effects which can fail and if we allow the transition, our machine would be in an invalid state.

Our use case is media playback. From `idle` to `loaded` you can try loading the video but if that fails you actually need to be back in the idle state.

**Comment by matthewp** [comment]
You want to use an intermediate state and [invoke](https://thisrobot.life/api/invoke.html) for this sort of thing. Invoke your external API call and use the result to determine what to do next. Something like this:

```js
// Only allow submission of a login and password is entered.
async function canSubmit(ctx) {
  return fetch(`/api/verify/${ctx.login}`);
}

const machine = createMachine({
  idle: state(
    transition('submit', 'complete',
      guard(canSubmit)
    )
  ),
  verifying: invoke(canSubmit,
    // If the API verified proceed to complete
    transition('done', 'complete', guard((ctx, ev) => !!ev.data)),

    // Otherwise go back to idle
    transition('done', 'idle')
  ),
  complete: state()
});
```

**Comment by victortwc** [comment]
I had the same with XState. The problem is that if every transition requires an async operation you suddenly have N extra states just for invocations. Wouldn't it make more sense to have guards supporting promises?

I understand it's not supported, we can close this. But maybe we can give it a bit more thought.

**Comment by matthewp** [comment]
Making guards async would mean that all transitions are async which means that the machine is in an invalid state part of the time. While your verification method is waiting the machine would still be in `idle` state and that means something else could send an event that moves it to another state. Then what happens when the async function completes? It can't continue on with the now invalid transition.

This is why transitions must be sync, so that the machine is always in a valid state.

Also I think this is just correct design. It's not true that your machine only has 2 states. The verification step *is* a state. You might want to show a loading indicator to your users so that they know verification is occurring, or something else.

**Comment by victortwc** [comment]
Crystal clear :)
